@startuml


cloud rocketmq

cloud canal

cloud 网关

node "内容facade" {
     [内容发布]
}

node "社区facade" {
     [社区氛围]
}

node "内容系统" {
     [内容存储]
}


 node "禁言系统" {
     [用户禁言]
 }
 node "举报系统" {
     [用户举报]
 }
 node "地址系统" {
      [地址信息]
 }

node "话题系统" {
     [话题信息]
}

node "用户系统" {
     [用户信息]
}

node "注册系统" {
     [注册信息]
}

node "安全系统" {
    [安全规则]
}

node "审核系统" {
    [审核任务]
}

node "消息系统" {
    [消息投递]
}

node "转码系统" {
    [转码任务]
}

package "算法" {
  node 打分系统
  node 标签系统
}

database 内容库

网关-->内容发布
网关-->注册信息
网关-->社区氛围
内容发布-right->注册信息
内容发布-->内容存储
内容发布-->安全规则
社区氛围-->用户举报
内容发布-->[用户信息]
社区氛围-->[用户禁言]
内容存储-->[地址信息]
内容存储-->[话题信息]
内容存储--> [消息投递]
内容存储<-->审核任务
内容存储<-->转码任务
内容存储-->内容库
内容库-left->canal:binlog同步
rocketmq<--canal:投递MQ
内容存储-left->rocketmq
打分系统<--rocketmq
标签系统<--rocketmq

@enduml