@startuml
start
:帖子库Canal变更数据;
:发送rocketmq;
:应用监听rocketmq;
:调用安检应用;
:修改帖子状态&任务TASKID;
stop

start
:应用监听审核rocketmq消息;
if(审核通过) then (true)
:修改审核通过状态;
else
:修改审核不通过状态&原因;
:投递到用户消息系统;
endif
stop

start
:兜底任务;
:每天晚上扫描全表初始化状态;
:投递到送检流程;
:每天晚上扫描全表已送审状态;
:主动查询审核结果;
stop

@enduml
