@startuml
!include <C4/C4_Context>
LAYOUT_WITH_LEGEND()

title 弹幕系统架构图

Person(user, "用户")
Person(user1, "运营")
Person(user2, "安检")

System_Boundary(relationContentProduction, "内容互动"){
     System(comment, "评论系统")
     System(barrage, "弹幕系统")
     System(admin, "互动后台")
     Rel_L(admin, barrage, "运营")
     Rel_R(admin, comment, "运营")
}

System_Ext(security,"风控系统")
System_Ext(userSystem,"用户系统")
System_Ext(audit, "审核系统")
System_Ext(message, "消息系统")
System_Ext(videoSystem, "媒体系统")
Rel(user, barrage, "发帖&生产工具")
Rel(user1,admin, "运营")

Rel(barrage, security, "安全规则")
Rel(barrage, userSystem, "用户认证&权限")
Rel(barrage, message, "发布消息")
Rel(barrage, audit, "发起审核")
Rel(barrage, videoSystem, "获取信息")
Rel_U(user2, audit, "审核")



@enduml