@startuml
!include <C4/C4_Container>
LAYOUT_WITH_LEGEND()

Person(user, "用户")

System_Boundary(item, "关系"){
    System(relation, "关系系统")
    System(follow, "关注系统")
}

System_Ext(feed, "场景Feed")
System_Ext(security,"安全系统")
System_Ext(userSystem,"用户系统")

Rel(user, relation, "点赞/收藏")
Rel(user, follow, "关注")
Rel_Neighbor(follow, relation, "依赖")
Rel(relation, security, "安全检查")
Rel(relation, userSystem, "用户校验")
Rel_L(feed, relation, "获取关系")
Rel_L(feed, follow, "获取关注")


@enduml