@startuml

cloud tt

node "关系facade" {
     [关系发布]
     [关注列表]
}

node "场景FEED" {
  [关系插件]<-left-[Feed组装]

}

node "关系系统" {
     [关系内容]
     [关系统计]
}

node "关系任务系统" {
   [关系统计任务]-left->[关系同步任务]
}

node "关注系统" {
     [关注信息]
}

node "消息系统" {
    [消息投递]
}

database 关系库

database 统计库

database redis

关系内容-->关系库
关系统计-->统计库
统计库<--关系统计任务
关系库<--关系统计任务
关系库-->tt
统计库-->tt

tt--> 关系统计任务
tt--> 关系同步任务

关系插件-->redis

关系系统<-right-关系插件
关系系统-right->redis

关系发布-->关系内容
消息投递<--关系同步任务

关注信息-->关系库

关注信息-->统计库

关注列表-->关注信息


@enduml