@startuml
start
:基本参数校验(长度/枚举值);
:校验参数是否传入当前登陆用户ID;
if(传入当前用户ID) then (true);
:拼装布隆过滤器数据,查询存在判断缓存;
if(缓存返回数据标识有一些存在) then (true);
:查询数据库;
endif
endif
:拼装布隆过滤器数据,查询存在判断缓存;
if(缓存返回数据标识有一些存在) then (true);
:拼装缓存数据,查询统计数据;
if(缓存数据查询有一些不在) then (true);
:查询数据库,更新缓存;
endif
endif
stop

@enduml
