@startuml
!include <C4/C4_Container>
LAYOUT_WITH_LEGEND()

title 评论应用架构图

Person(user, "用户")
Person(user1, "运营")
Person(user2, "安检")

System_Boundary(interaction, "内容互动"){
    Container_Boundary(commentBoundary, "评论") {
          Container(commentFacade, "评论应用","Spring-boot")
          Container(commentService, "评论服务","Spring-boot")
          Container(commentJobService, "评论任务服务","Spring-boot")
          ContainerDb(commentDatabase, "数据库", "Mysql")
          ContainerQueue(commentQueue, "弹幕队列", "RocketMq")
          Rel(commentFacade, commentService, "调用")
          Rel_L(commentService, commentDatabase, "保存")
          Rel(commentService, commentQueue, "发送")
          Rel(commentJobService, commentService, "调用")
          Rel_R(commentQueue, commentJobService, "消息接收")
    }

    Container_Boundary(InteractCommonBoundary, "互动通用"){
        Container(interactAdmin, "互动后台","Spring-boot")
    }
     System_Boundary(relationBoundary, "关系互动"){
             System(relation, "关系系统")
     }

    Rel_R(interactAdmin, commentService, "调用")
}

System_Ext(security,"风控系统")
System_Ext(userSystem,"认证系统")
System_Ext(forbidden, "禁闭系统")
System_Ext(audit, "审核系统")
System_Ext(message, "消息系统")
System_Ext(video, "媒体系统")
System_Ext(gateway,"网关系统")



Rel(user, gateway, "发&看评论")
Rel(gateway,commentFacade, "发&看弹幕")
Rel(user1,interactAdmin, "运营")

Rel(commentFacade, security, "安全规则")
Rel(commentFacade, userSystem, "用户认证&权限")
Rel(commentFacade, forbidden, "获取禁闭列表")
Rel(commentJobService, message, "发布消息")
Rel(commentJobService, audit, "发起审核")
Rel(commentService, video, "获取媒体信息")
Rel(commentService, relation, "点赞")
Rel_R(user2, audit, "审核")







@enduml


