@startuml
!include <C4/C4_Context>
LAYOUT_WITH_LEGEND()

title 评论系统架构图

Person(user, "用户")
Person(user1, "运营")
Person(user2, "安检")

System_Boundary(relationContentProduction, "内容互动"){
     System(comment, "评论系统")
     System(barrage, "弹幕系统")
     System(admin, "互动后台")
     Rel_R(admin, barrage, "运营")
     Rel_R(admin, comment, "运营")
}

System_Ext(security,"风控系统")
System(relation,"关系互动")
System_Ext(userSystem,"用户系统")
System_Ext(audit, "审核系统")
System_Ext(message, "消息系统")
System_Ext(videoSystem, "媒体系统")
Rel(user, comment, "发评论")
Rel(user1,admin, "运营")

Rel(comment, security, "安全规则")
Rel(comment, userSystem, "用户认证&权限")
Rel(comment, message, "发布消息")
Rel(comment, videoSystem, "获取信息")
Rel(comment, relation, "获取信息")
Rel(comment, audit, "发起审核")
Rel_U(user2, audit, "审核")




@enduml