@startuml
!include <C4/C4_Sequence>
SHOW_INDEX()
SHOW_LEGEND()

title 弹幕送审时序图
System(rocketmq,"MQ")
System(job,"任务中间件系统")
Container_Boundary(barrageJobService, "弹幕任务服务")
    Component(auditComponent, "送审组件", "component", "弹幕送审")
    Component(messageComponent, "消息组件", "component", "消息组件")
Boundary_End()

Container_Boundary(barrageService, "弹幕服务")
    Component(barrageComponent, "弹幕服务组件", "component", "弹幕服务组件")
Boundary_End()

System(auditSystem,"审核系统")
System(messageSystem,"消息系统")
ComponentDb(db, "弹幕数据库", "Mysql")

== 送审 ==
Rel(rocketmq, auditComponent, "接收到数据库变更消息")
Rel(auditComponent, auditComponent, "查看状态")
alt 状态是待送审
 Rel(auditComponent, auditSystem, "调用审核系统API")
 Rel(auditSystem, auditComponent, "返回")
 Rel(auditComponent,barrageComponent , "调用服务")
 Rel(barrageComponent,db , "修改状态&存储相关审核信息")
 Rel(db,barrageComponent , "返回")
 Rel(barrageComponent,auditComponent , "返回")
end
Rel(auditComponent,rocketmq , "完成处理")

== 审核处理 ==
Rel(auditSystem, auditComponent, "审核完成")
Rel(auditComponent, barrageComponent, "修改数据库&记录信息")
Rel(barrageComponent,db , "修改状态&存储相关审核信息")
Rel(db,barrageComponent , "返回")
Rel(barrageComponent,auditComponent , "返回")
Rel(auditComponent,auditSystem , "完成处理")


== 消息处理 ==
Rel(rocketmq, messageComponent, "接收审核后信息")
Rel(messageComponent, messageComponent, "查看状态")
alt 状态是审核未通过
 Rel(messageComponent, messageSystem, "发送审核未通过消息")
 Rel(messageSystem, messageComponent, "返回")
end
Rel(messageComponent,rocketmq , "完成处理")


== 兜底处理 ==
Rel(job, auditComponent, "每30分钟扫描")
Rel(auditComponent, auditComponent, "查看状态")
alt 状态是待送审
 Rel(auditComponent, auditComponent, "送审逻辑")
else 状态是已送审&30分钟无结果
 Rel(auditComponent, auditSystem, "查询状态")
 Rel(auditSystem, auditComponent, "返回")
end
Rel(auditComponent,job , "完成处理")


@enduml