@startuml
!include <C4/C4_Component>
LAYOUT_WITH_LEGEND()

title 关注/点赞/收藏链路组件图

System(rocketmq,"MQ")
System(auditSystem,"审核系统")
System(job,"任务中间件系统")

Container_Boundary(barrageJobService, "弹幕任务服务"){
    Component(auditComponent, "送审组件", "component", "弹幕送审")
    Component(messageComponent, "消息组件", "component", "消息组件")
}
Container_Boundary(barrageService, "弹幕服务"){
    Component(barrageComponent, "弹幕服务组件", "component", "弹幕服务组件")
}

System(messageSystem,"消息系统")
ComponentDb(db, "弹幕数据库", "Mysql")

Rel(rocketmq, auditComponent, "接收到数据库变更消息")
Rel(rocketmq, messageComponent, "接收到数据库变更消息")
Rel(job, auditComponent, "兜底任务")
BiRel_L(auditComponent, auditSystem, "互相调用")
Rel(messageComponent, messageSystem, "发送&接收消息")
Rel(auditComponent, barrageComponent, "调用服务")
Rel_L(barrageComponent, db, "修改&保存数据库")






@enduml