@startuml
!include <C4/C4_Sequence>
SHOW_INDEX()
SHOW_LEGEND()

Person(user, "用户")
System(gateway,"网关系统")

Rel(user, gateway, "请求")
Rel(gateway, gateway, "用户身份验证")

Container_Boundary(barrageFacade, "弹幕应用")
    Component(checkComponent, "校验组件", "component", "IP校验&安全检验")
    Component(authComponent, "权限组件", "component", "用户权限检验")
Boundary_End()

Container_Boundary(barrageService, "弹幕服务")
    Component(barrageComponent, "弹幕服务组件", "component", "弹幕服务组件")
    Component(profileComponent, "视频打点组件", "component", "视频打点组件")
    Component(barrageStatComponent, "弹幕统计组件", "component", "统计组件")
    Component(cacheComponent, "弹幕缓存组件", "component", "缓存组件")
Boundary_End()

Container_Boundary(relationService, "关系统计服务")
    Component(statComponent, "统计公共组件", "component", "统计公共组件")
Boundary_End()
System(security,"风控系统")
System(userSystem,"用户系统")
System(videoSystem,"视频系统")
System(rocketmq,"MQ")
System(redis,"缓存","redis")
ComponentDb(db, "数据库", "Mysql")

Rel(gateway, checkComponent, "发起请求")

Rel(checkComponent, security, "获取规则")
Rel(security,checkComponent, "IP校验&安全检验不通过错误")

Rel(checkComponent, videoSystem, "视频信息获取")
Rel(videoSystem,checkComponent, "视频信息判断不通过错误")
Rel(checkComponent, authComponent, "权限控制")
Rel(authComponent, userSystem, "用户信息获取")
Rel(userSystem,authComponent, "实名认证&是否禁闭不通过返回")

Rel(authComponent, barrageComponent, "发起请求")
Rel(barrageComponent, db, "保存数据")
Rel(db, barrageComponent, "返回")
Rel(barrageComponent, authComponent, "返回")
Rel(authComponent, gateway, "返回")
Rel(gateway, user, "返回")

== profile更新 ==
Rel(rocketmq, profileComponent, "监听到变更")
alt redis10分钟幂未通过
Rel(profileComponent, rocketmq, "返回")
end
alt 弹幕状态变更从未审核变成审核通过
  Rel(profileComponent, statComponent, "对分钟列进行+")
  Rel(statComponent, profileComponent, "数据库返回")
else 弹幕状态变更从审核通过变成未通过
  Rel(profileComponent, statComponent, "对分钟列进行-")
  Rel(statComponent, profileComponent, "数据库返回")
end
alt 分钟列如果小于10
Rel(profileComponent, cacheComponent, "更新视频打点缓存")
Rel(cacheComponent, redis, "更新缓存")
Rel(redis, cacheComponent, "返回")
Rel(cacheComponent, profileComponent, "返回")
end
Rel(profileComponent, rocketmq, "返回")


== 计数器更新 ==
Rel(rocketmq, barrageStatComponent, "监听到变更")
alt redis10分钟幂未通过
Rel(barrageStatComponent, rocketmq, "返回")
end
alt 弹幕状态变更从未审核变成审核通过
  Rel(barrageStatComponent, db, "统计数据进行+")
  Rel(db, barrageStatComponent, "数据库返回")
else 弹幕状态变更从审核通过变成未通过
  Rel(barrageStatComponent, db, "统计数据进行-")
  Rel(db, barrageStatComponent, "数据库返回")
end
Rel(barrageStatComponent, rocketmq, "完成更新")
@enduml
