@startuml
!include <C4/C4_Container>
LAYOUT_WITH_LEGEND()

title 投稿系统应用架构图

Person(user, "用户")
Person(user1, "运营")
Person(user2, "安检")

System_Boundary(contentProduction, "内容生产"){
    System_Boundary(mediaProcessBoundary, "媒体处理") {
          Container(mediaProcessService, "媒体处理","Spring-boot")
          Container(postService, "投稿服务","Spring-boot")
          Container(postReadService, "帖子读服务","Spring-boot")
          ContainerDb(postDatabase, "帖子数据库", "Mysql")
          ContainerQueue(postQueue, "帖子队列", "RocketMq")

   }
}

System_Ext("dts","任务驱动")






@enduml


