@startuml
!include <C4/C4_Context>
LAYOUT_WITH_LEGEND()

title 媒体处理架构图

Person(user, "用户")
Person(user1, "运营")
System("fun","云服务函数计算")
System("videoPaas","视频云PAAS")

System_Boundary(contentProduction, "内容生产"){
     System(media_process, "媒体处理")
     System(post, "投稿系统")
     System(postTool, "工具系统")
     Rel_R(post, media_process, "媒体处理")
     Rel_L(post, postTool, "工具")
}
Rel(user,post,"发布")
Rel(user1,media_process,"发布")
Rel(media_process,fun,"集成")
Rel(media_process,videoPaas,"集成")

@enduml