@startuml
!include <C4/C4_Sequence>
SHOW_INDEX()
SHOW_LEGEND()

title 评论送审时序图
System(rocketmq,"MQ")
System(job,"任务中间件系统")
Container_Boundary(commentJobService, "评论任务服务")
    Component(auditComponent, "送审组件", "component", "评论送审")
    Component(messageComponent, "消息组件", "component", "消息组件")
Boundary_End()

Container_Boundary(commentService, "评论服务")
    Component(commentComponent, "评论服务组件", "component", "评论服务组件")
Boundary_End()

System_Ext(auditSystem,"审核系统")
System_Ext(messageSystem,"消息系统")
ComponentDb(db, "评论数据库", "Mysql")

== 送审 ==
Rel(rocketmq, auditComponent, "接收到数据库变更消息")
Rel(auditComponent, auditComponent, "查看状态")
alt 状态是待送审
 Rel(auditComponent, auditSystem, "调用审核系统API")
 Rel(auditSystem, auditComponent, "返回")
 Rel(auditComponent,commentComponent , "调用服务")
 Rel(commentComponent,db , "修改状态&存储相关审核信息")
 Rel(db,commentComponent , "返回")
 Rel(commentComponent,auditComponent , "返回")
end
Rel(auditComponent,rocketmq , "完成处理")

== 审核处理 ==
Rel(auditSystem, auditComponent, "审核完成")
Rel(auditComponent, commentComponent, "修改数据库&记录信息")
Rel(commentComponent,db , "修改状态&存储相关审核信息")
Rel(db,commentComponent , "返回")
Rel(commentComponent,auditComponent , "返回")
Rel(auditComponent,auditSystem , "完成处理")


== 消息处理 ==
Rel(rocketmq, messageComponent, "接收审核后信息")
Rel(messageComponent, messageComponent, "查看状态")
alt 状态是审核未通过
 Rel(messageComponent, messageSystem, "发送审核未通过消息")
 Rel(messageSystem, messageComponent, "返回")
end
Rel(messageComponent,rocketmq , "完成处理")


== 兜底处理 ==
Rel(job, auditComponent, "每30分钟扫描")
Rel(auditComponent, commentComponent, "查询超过30分钟异常数据")
Rel(commentComponent, db, "查询")
Rel(db, commentComponent, "返回")
Rel(commentComponent, auditComponent, "返回")
alt 状态是待送审
 Rel(auditComponent, auditComponent, "送审逻辑")
else 状态是已送审&30分钟无结果
 Rel(auditComponent, auditSystem, "查询状态")
 Rel(auditSystem, auditComponent, "返回")
end
Rel(auditComponent,job , "完成处理")


@enduml