@startuml
!include <C4/C4_Component>
LAYOUT_WITH_LEGEND()

title 评论送审组件图

System(rocketmq,"MQ")
System_Ext(auditSystem,"审核系统")
System(job,"任务中间件系统")

Container_Boundary(commentJobService, "评论任务服务"){
    Component(auditComponent, "送审组件", "component", "评论送审")
    Component(messageComponent, "消息组件", "component", "消息组件")
}
Container_Boundary(commentService, "评论服务"){
    Component(commentComponent, "评论服务组件", "component", "评论服务组件")
}

System_Ext(messageSystem,"消息系统")
ComponentDb(db, "评论数据库", "Mysql")

Rel(rocketmq, auditComponent, "接收到数据库变更消息")
Rel(rocketmq, messageComponent, "接收到数据库变更消息")
Rel(job, auditComponent, "兜底任务")
BiRel_L(auditComponent, auditSystem, "互相调用")
Rel(messageComponent, messageSystem, "发送&接收消息")
Rel(auditComponent, commentComponent, "调用服务")
Rel_L(commentComponent, db, "修改&保存数据库")






@enduml