@startuml
start
:监听消息;
:统计更新策略选择;
switch (策略)
case (统计数小于10000)
  :每列变化都主动更新缓存;
case (统计数>10000)
  :每取模1000在0-100上次更新一次;
case (其他列更新)
  :对库里所有数据更新一次;
endswitch
stop


start
:监听消息;
:拼装相关KEY,更新布隆过滤器;
stop


@enduml
