@startuml

cloud rocketmq

cloud canal

cloud 网关

node "评论facade" {
     [评论]
}
node "评论系统" {
     [评论存储]
}

node "社区facade" {
     [社区氛围]
}

node "禁言系统" {
     [用户禁言]
}
node "举报系统" {
     [用户举报]
}

node "用户系统" {
     [用户信息]
}

node "注册系统" {
     [注册信息]
}

node "安全系统" {
    [安全规则]
}

node "审核系统" {
    [审核任务]
}

node "消息系统" {
    [消息投递]
}

node "转码系统" {
    [转码任务]
}

database 评论库

网关-->评论
网关-->注册信息
网关-->社区氛围
评论-right->注册信息
评论-->评论存储
评论-->安全规则
社区氛围-->用户举报
评论-->[用户信息]
社区氛围-->[用户禁言]
评论存储--> [消息投递]
评论存储<-->审核任务
评论存储<-->转码任务

评论库<--评论存储
评论库-->canal:binlog同步
canal-right->rocketmq:投递MQ
rocketmq-right->评论存储



@enduml