@startuml
!include <C4/C4_Component>
LAYOUT_WITH_LEGEND()

title 上传链路组件图

Person(user, "用户")

Container_Boundary(postFacade, "投稿应用"){
    Component(checkComponent, "校验组件", "component", "安全检验")
    Component(userComponent, "实名组件", "component", "用户实名检验")
    Component(authComponent, "权限组件", "component", "用户权限检验")
}

Container_Boundary(postService, "投稿服务"){
    Component(uploadComponent, "上传组件", "component", "上传令牌服务")
    Rel(checkComponent, authComponent, "权限规则")
    Rel(authComponent, uploadComponent, "上传")
}

Container_Boundary("objectStorage", "对象存储"){
    System_Ext(oss,"阿里OSS")
    System_Ext(cos,"腾讯COS")
}

System_Ext(gateway,"网关系统")
System_Ext(security,"安全系统")
System_Ext(userSystem,"用户系统")
ContainerDb(db, "投稿数据库", "Mysql","上传记录")



Rel_R(user, gateway, "上传")
Rel(user, objectStorage, "上传")
Rel_R(gateway, checkComponent, "IP校验")
Rel_R(checkComponent, security, "安全规则")
Rel_R(authComponent, userSystem, "用户认证&权限")
Rel_L(uploadComponent, objectStorage, "获取StsToken")
Rel_R(uploadComponent, db, "存储数据")




@enduml