@startuml
!include <C4/C4_Component>
LAYOUT_WITH_LEGEND()

title 关注/点赞/收藏查询组件图

Person(user, "用户")
System(gateway,"网关系统")

Rel_R(user, gateway, "请求")

System_Boundary(feed, "Feed应用"){
   Component(listFeedComponent, "关注/点赞列表组件", "component", "关注/点赞列表Feed")
   Component(relationClientComponent, "关系客户端组件", "component", "关系客户端组件")
   Rel_L(listFeedComponent, relationClientComponent, "本地客户端发起互动组件数据")
}


Container_Boundary(relationReadService, "关系读服务"){
    Component(listComponent, "列表组件", "component", "列表组件")
    Component(relationComponent, "关系组件", "component", "关系关注")
    Component(statComponent, "计数器组件", "component", "计数器更新")
 }
ComponentDb(redis, "缓存", "redis")
ComponentDb(db, "数据库", "表格数据库")

Rel(gateway,listFeedComponent,"请求")
Rel(listFeedComponent, listComponent, "feed应用发起请求")

Rel(relationClientComponent, relationComponent, "返回")
Rel(relationClientComponent, redis, "查询缓存数据")
Rel(relationClientComponent, statComponent, "返回")
Rel(listComponent, db, "查询数据返回IDS")
Rel(statComponent, db, "查询数据")
Rel(relationComponent, db, "查询数据")





@enduml