@startuml
start
:监听消息;
:redis10分钟幂等校验;
if(幂等校验通过) then (true);
:统计策略选择;
switch (策略)
case (接入类型没有detail)
  :对相关列进行+-;
case (有detail&小于10000&上次count时间小于特定值)
  :对相关列进行+-;
case (有detail&&小于10000&上次count时间大与特定值)
  :对数据调用详情数据进行count;
case (其他)
  :对相关列进行+-;
endswitch
endif
stop

@enduml
