@startuml
!include <C4/C4_Sequence>
SHOW_INDEX()
SHOW_LEGEND()
title 发送评论时序图
Person(user, "用户")
System(gateway,"网关系统")

Rel(user, gateway, "请求")
Rel(gateway, gateway, "用户身份验证")

Container_Boundary(commentFacade, "评论应用")
    Component(checkComponent, "校验组件", "component", "检验权限组件")
    Component(facadeCacheComponent, "前台缓存组件", "component", "缓存组件")
Boundary_End()

Container_Boundary(commentService, "评论服务")
    Component(commentComponent, "评论服务组件", "component", "评论服务组件")
    Component(commentStatComponent, "评论统计组件", "component", "统计组件")
Boundary_End()

Container_Boundary(relationService, "关系统计服务")
    Component(statComponent, "统计公共组件", "component", "统计公共组件")
Boundary_End()
System_Ext(security,"风控系统")
System_Ext(userSystem,"用户系统")
System_Ext(videoSystem,"视频系统")
System(rocketmq,"MQ")
System(redis,"缓存","redis")
ComponentDb(db, "数据库", "Mysql")

Rel(gateway, checkComponent, "发起请求")

Rel(checkComponent, security, "获取规则")
Rel(security,checkComponent, "IP校验&安全检验不通过错误返回")


Rel(checkComponent, facadeCacheComponent, "请求")
Rel(facadeCacheComponent, videoSystem, "获取视频信息，先缓存再服务")
BiRel(facadeCacheComponent, redis, "请求缓存")
Rel(videoSystem, facadeCacheComponent, "返回")
Rel(facadeCacheComponent, checkComponent, "返回")
Rel(checkComponent, checkComponent, "检查视频是否存在?")


Rel(checkComponent, userSystem, "用户信息获取")
Rel(userSystem,checkComponent, "实名认证不通过直接返回")

Rel(checkComponent, facadeCacheComponent, "请求")
Rel(facadeCacheComponent, userSystem, "获取用户是否禁言,先缓存再服务")
BiRel(facadeCacheComponent, redis, "请求缓存")
Rel(userSystem, facadeCacheComponent, "返回")
Rel(facadeCacheComponent, checkComponent, "返回")
Rel(checkComponent, checkComponent, "检查用户是否禁言?")


Rel(checkComponent, commentComponent, "发起请求")
Rel(commentComponent, commentComponent, "检查")
Rel(commentComponent, db, "保存数据")
Rel(db, commentComponent, "返回")
Rel(commentComponent, checkComponent, "返回")
Rel(checkComponent, gateway, "返回")
Rel(gateway, user, "返回")


== 计数器更新 ==
Rel(rocketmq, commentStatComponent, "监听到变更")
Rel(commentStatComponent, commentStatComponent, "redis10分钟幂未通过,返回")
alt 弹幕状态变更
  Rel(commentStatComponent, db, "统计数据进行+")
  Rel(db, commentStatComponent, "数据库返回")
end
Rel(commentStatComponent, rocketmq, "完成更新")

@enduml
